baseURL = 'https://www.linux4jamaica.org'
languageCode = 'en-us'
title = 'ðŸ‡¯ðŸ‡² Linux4Jamaica'
description = "Upcycled Computers for Educators in JA"
theme = 'ananke'
resourceDir = "../resources"

googleAnalytics = 'G-GEM1D9JCBT'
enableRobotsTXT = true
canonifyURLs = true 

SectionPagesMenu = "main"

[params]
  text_color = ""
  author = ""
  favicon = "favicon.ico"
  site_logo = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  recent_posts_number = 3
